import {
  CONTENT_MESSAGE,
  PAGE_HOOK_SOURCE,
  type GeneratedBundle
} from "./shared/messages";

export interface GeneratedModWrapperOptions {
  bundle: GeneratedBundle;
  projectId?: string;
  scriptId: string;
}

/**
 * Build a single self-contained user-script string from the generated bundle.
 * The emitted script installs a tiny shared runtime in the user-script world,
 * runs generated JS in a mod context, and wraps callbacks registered by that
 * context so later failures can be attributed to the same generated mod.
 */
export const buildGeneratedModUserScriptCode = ({
  bundle,
  projectId,
  scriptId
}: GeneratedModWrapperOptions): string => {
  const cssLiteral = JSON.stringify(bundle.css || "");
  const idLiteral = JSON.stringify(scriptId);
  const modIdLiteral = JSON.stringify(bundle.mod_id || scriptId);
  const modNameLiteral = JSON.stringify(bundle.name || "Conjure customization");
  const projectIdLiteral = JSON.stringify(projectId || "");

  return [
    buildCssInjectionCode(cssLiteral, idLiteral),
    buildGeneratedModRuntimeCode(),
    buildDomTaggingSetupCode(modIdLiteral),
    "(function () {",
    `  var __conjureRuntime = window.__CONJURE_GENERATED_MOD_RUNTIME__;`,
    "  var __conjureContext = __conjureRuntime.createContext({",
    `    projectId: ${projectIdLiteral},`,
    `    scriptId: ${idLiteral},`,
    `    modId: ${modIdLiteral},`,
    `    modName: ${modNameLiteral}`,
    "  });",
    "  var __conjureRunToken = __conjureRuntime.enter(__conjureContext);",
    "  try {",
    bundle.js || "",
    "  } catch (__conjureError) {",
    "    __conjureRuntime.report(__conjureContext, __conjureError, 'sync');",
    "    throw __conjureError;",
    "  } finally {",
    "    __conjureRuntime.exit(__conjureRunToken);",
    buildDomTaggingFinalizerCode(modIdLiteral)
      .split("\n")
      .map((line) => `    ${line}`)
      .join("\n"),
    "  }",
    "})();"
  ].join("\n");
};

const buildCssInjectionCode = (cssLiteral: string, idLiteral: string): string =>
  [
    "(function () {",
    `  var __conjureCss = ${cssLiteral};`,
    "  if (__conjureCss && __conjureCss.trim()) {",
    "    var __existing = document.querySelector('style[data-conjure=' + JSON.stringify(" +
      idLiteral +
      ") + ']');",
    "    if (!__existing) {",
    "      var __style = document.createElement('style');",
    `      __style.setAttribute('data-conjure', ${idLiteral});`,
    "      __style.textContent = __conjureCss;",
    "      (document.head || document.documentElement).appendChild(__style);",
    "    }",
    "  }",
    "})();"
  ].join("\n");

const buildGeneratedModRuntimeCode = (): string => {
  const messageTypeLiteral = JSON.stringify(CONTENT_MESSAGE.GENERATED_MOD_ERROR);
  const pageHookSourceLiteral = JSON.stringify(PAGE_HOOK_SOURCE);

  return [
    "(function () {",
    "  var __root = window;",
    "  if (__root.__CONJURE_GENERATED_MOD_RUNTIME__) return;",
    "  var __messageType = " + messageTypeLiteral + ";",
    "  var __pageHookSource = " + pageHookSourceLiteral + ";",
    "  var __contextStack = [];",
    "  var __eventTargetPrototype = typeof EventTarget !== 'undefined' && EventTarget.prototype;",
    "  var __originalAddEventListener = __eventTargetPrototype && __eventTargetPrototype.addEventListener;",
    "  var __originalRemoveEventListener = __eventTargetPrototype && __eventTargetPrototype.removeEventListener;",
    "  var __originalSetTimeout = window.setTimeout;",
    "  var __originalSetInterval = window.setInterval;",
    "  var __originalRequestAnimationFrame = window.requestAnimationFrame;",
    "  var __hasWeakSet = typeof WeakSet === 'function';",
    "  var __hasWeakMap = typeof WeakMap === 'function';",
    "  var __listenerMaps = __hasWeakMap ? new WeakMap() : null;",
    "  var __isObject = function (value) {",
    "    return (typeof value === 'object' && value !== null) || typeof value === 'function';",
    "  };",
    "  var __safeString = function (value) {",
    "    if (typeof value === 'string') return value;",
    "    if (value === null) return 'null';",
    "    if (typeof value === 'undefined') return 'undefined';",
    "    if (typeof value === 'number' || typeof value === 'boolean' || typeof value === 'bigint') return String(value);",
    "    try {",
    "      return JSON.stringify(value);",
    "    } catch (_error) {",
    "      try {",
    "        return Object.prototype.toString.call(value);",
    "      } catch (_nestedError) {",
    "        return 'Unknown generated mod error';",
    "      }",
    "    }",
    "  };",
    "  var __serializeError = function (error) {",
    "    if (error instanceof Error) {",
    "      return {",
    "        message: error.message || error.name || 'Generated mod error',",
    "        stack: error.stack || '',",
    "        line: typeof error.lineNumber === 'number' ? error.lineNumber : undefined,",
    "        column: typeof error.columnNumber === 'number' ? error.columnNumber : undefined",
    "      };",
    "    }",
    "    return { message: __safeString(error), stack: '' };",
    "  };",
    "  var __postFallback = function (reportMessage) {",
    "    try {",
    "      window.postMessage({",
    "        source: __pageHookSource,",
    "        type: __messageType,",
    "        payload: reportMessage.payload",
    "      }, '*');",
    "    } catch (_error) {",
    "      // Reporting is best effort only.",
    "    }",
    "  };",
    "  var __sendReport = function (reportMessage) {",
    "    var sentDirect = false;",
    "    try {",
    "      if (typeof chrome !== 'undefined' && chrome.runtime && typeof chrome.runtime.sendMessage === 'function') {",
    "        sentDirect = true;",
    "        chrome.runtime.sendMessage(reportMessage, function () {",
    "          try {",
    "            if (chrome.runtime.lastError) __postFallback(reportMessage);",
    "          } catch (_error) {",
    "            // Ignore status-check failures from optional messaging.",
    "          }",
    "        });",
    "      }",
    "    } catch (_error) {",
    "      sentDirect = false;",
    "    }",
    "    if (!sentDirect) __postFallback(reportMessage);",
    "  };",
    "  var __markReported = function (context, thrown) {",
    "    if (!context || !__isObject(thrown) || !context.reportedObjects) return false;",
    "    try {",
    "      if (context.reportedObjects.has(thrown)) return true;",
    "      context.reportedObjects.add(thrown);",
    "    } catch (_error) {",
    "      return false;",
    "    }",
    "    return false;",
    "  };",
    "  var __report = function (context, thrown, source, metadata) {",
    "    if (!context || __markReported(context, thrown)) return;",
    "    var serialized = __serializeError(thrown);",
    "    var payload = {",
    "      projectId: context.projectId,",
    "      scriptId: context.scriptId,",
    "      modId: context.modId,",
    "      modName: context.modName,",
    "      url: String(location.href || ''),",
    "      message: String(serialized.message || 'Generated mod error').slice(0, 12000),",
    "      stack: String(serialized.stack || '').slice(0, 64000),",
    "      source: source",
    "    };",
    "    var line = metadata && typeof metadata.line === 'number' ? metadata.line : serialized.line;",
    "    var column = metadata && typeof metadata.column === 'number' ? metadata.column : serialized.column;",
    "    if (typeof line === 'number') payload.line = line;",
    "    if (typeof column === 'number') payload.column = column;",
    "    __sendReport({ type: __messageType, payload: payload });",
    "  };",
    "  var __currentContext = function () {",
    "    return __contextStack.length ? __contextStack[__contextStack.length - 1].context : null;",
    "  };",
    "  var __enter = function (context) {",
    "    var frame = { context: context };",
    "    __contextStack.push(frame);",
    "    return frame;",
    "  };",
    "  var __exit = function (frame) {",
    "    for (var index = __contextStack.length - 1; index >= 0; index -= 1) {",
    "      if (__contextStack[index] === frame) {",
    "        __contextStack.splice(index, 1);",
    "        return;",
    "      }",
    "    }",
    "  };",
    "  var __captureRejectedResult = function (result, context) {",
    "    if (!result || typeof result.then !== 'function') return result;",
    "    try {",
    "      result.catch(function (error) {",
    "        __report(context, error, 'promise_rejection');",
    "      });",
    "    } catch (_error) {",
    "      // Non-standard thenables may throw while attaching rejection handlers.",
    "    }",
    "    return result;",
    "  };",
    "  var __runCallback = function (context, source, callback, thisArg, args) {",
    "    var frame = __enter(context);",
    "    try {",
    "      return __captureRejectedResult(callback.apply(thisArg, args), context);",
    "    } catch (error) {",
    "      __report(context, error, source);",
    "      throw error;",
    "    } finally {",
    "      __exit(frame);",
    "    }",
    "  };",
    "  var __wrapCallback = function (context, callback, source) {",
    "    if (!context || typeof callback !== 'function') return callback;",
    "    return function () {",
    "      return __runCallback(context, source, callback, this, arguments);",
    "    };",
    "  };",
    "  var __listenerKey = function (type, options) {",
    "    var capture = false;",
    "    if (typeof options === 'boolean') capture = options;",
    "    else if (options && typeof options === 'object') capture = Boolean(options.capture);",
    "    return String(type) + '::' + String(capture);",
    "  };",
    "  var __getContextListenerMap = function (context, listener) {",
    "    if (!__listenerMaps || !context || !__isObject(listener)) return null;",
    "    var byContext = __listenerMaps.get(listener);",
    "    if (!byContext) {",
    "      byContext = __hasWeakMap ? new WeakMap() : null;",
    "      if (!byContext) return null;",
    "      __listenerMaps.set(listener, byContext);",
    "    }",
    "    var byKey = byContext.get(context);",
    "    if (!byKey) {",
    "      byKey = {};",
    "      byContext.set(context, byKey);",
    "    }",
    "    return byKey;",
    "  };",
    "  var __rememberWrappedListener = function (context, type, listener, options, wrapped) {",
    "    var byKey = __getContextListenerMap(context, listener);",
    "    if (!byKey) return;",
    "    byKey[__listenerKey(type, options)] = wrapped;",
    "  };",
    "  var __recallWrappedListener = function (context, type, listener, options) {",
    "    if (!__listenerMaps || !context || !__isObject(listener)) return listener;",
    "    var byContext = __listenerMaps.get(listener);",
    "    var byKey = byContext && byContext.get(context);",
    "    return (byKey && byKey[__listenerKey(type, options)]) || listener;",
    "  };",
    "  var __wrapEventListener = function (context, type, listener, options) {",
    "    if (!context || !listener) return listener;",
    "    if (typeof listener === 'function') {",
    "      var wrappedFunction = __wrapCallback(context, listener, 'event_listener');",
    "      __rememberWrappedListener(context, type, listener, options, wrappedFunction);",
    "      return wrappedFunction;",
    "    }",
    "    if (listener && typeof listener.handleEvent === 'function') {",
    "      var wrappedObject = {",
    "        handleEvent: function () {",
    "          return __runCallback(context, 'event_listener', listener.handleEvent, listener, arguments);",
    "        }",
    "      };",
    "      __rememberWrappedListener(context, type, listener, options, wrappedObject);",
    "      return wrappedObject;",
    "    }",
    "    return listener;",
    "  };",
    "  if (__originalAddEventListener && __originalRemoveEventListener) {",
    "    __eventTargetPrototype.addEventListener = function (type, listener, options) {",
    "      return __originalAddEventListener.call(this, type, __wrapEventListener(__currentContext(), type, listener, options), options);",
    "    };",
    "    __eventTargetPrototype.removeEventListener = function (type, listener, options) {",
    "      return __originalRemoveEventListener.call(this, type, __recallWrappedListener(__currentContext(), type, listener, options), options);",
    "    };",
    "  }",
    "  window.setTimeout = function (callback) {",
    "    var args = Array.prototype.slice.call(arguments);",
    "    args[0] = __wrapCallback(__currentContext(), callback, 'timer');",
    "    return __originalSetTimeout.apply(this, args);",
    "  };",
    "  window.setInterval = function (callback) {",
    "    var args = Array.prototype.slice.call(arguments);",
    "    args[0] = __wrapCallback(__currentContext(), callback, 'interval');",
    "    return __originalSetInterval.apply(this, args);",
    "  };",
    "  if (typeof __originalRequestAnimationFrame === 'function') {",
    "    window.requestAnimationFrame = function (callback) {",
    "      return __originalRequestAnimationFrame.call(this, __wrapCallback(__currentContext(), callback, 'animation_frame'));",
    "    };",
    "  }",
    "  __root.__CONJURE_GENERATED_MOD_RUNTIME__ = {",
    "    createContext: function (metadata) {",
    "      return {",
    "        projectId: String(metadata.projectId || ''),",
    "        scriptId: String(metadata.scriptId || ''),",
    "        modId: String(metadata.modId || metadata.scriptId || 'unknown'),",
    "        modName: String(metadata.modName || 'Conjure customization'),",
    "        reportedObjects: __hasWeakSet ? new WeakSet() : null",
    "      };",
    "    },",
    "    enter: __enter,",
    "    exit: __exit,",
    "    report: __report",
    "  };",
    "})();"
  ].join("\n");
};

const buildDomTaggingSetupCode = (modIdLiteral: string): string =>
  [
    "(function () {",
    `  var __conjureModId = ${modIdLiteral};`,
    "  var __conjureCounter = 0;",
    "  var __originalCreateElement = document.createElement.bind(document);",
    "  var __originalCreateElementNS = document.createElementNS.bind(document);",
    "  var __tagNode = function (node) {",
    "    try {",
    "      if (!__conjureModId || !node) return node;",
    "      var nodes = [];",
    "      if (node.nodeType === 1) nodes.push(node);",
    "      if (node.nodeType === 11 || node.nodeType === 1) {",
    "        var children = node.querySelectorAll ? node.querySelectorAll('*') : [];",
    "        for (var index = 0; index < children.length; index += 1) nodes.push(children[index]);",
    "      }",
    "      for (var itemIndex = 0; itemIndex < nodes.length; itemIndex += 1) {",
    "        var element = nodes[itemIndex];",
    "        if (!element.setAttribute) continue;",
    "        if (!element.hasAttribute('data-conjure-mod-id')) {",
    "          element.setAttribute('data-conjure-mod-id', __conjureModId);",
    "        }",
    "        if (!element.hasAttribute('data-conjure-owned')) {",
    "          element.setAttribute('data-conjure-owned', 'true');",
    "        }",
    "        if (!element.hasAttribute('data-conjure-element-id')) {",
    "          __conjureCounter += 1;",
    "          element.setAttribute('data-conjure-element-id', __conjureModId + '-' + __conjureCounter);",
    "        }",
    "      }",
    "    } catch (_error) {",
    "      return node;",
    "    }",
    "    return node;",
    "  };",
    "  window.__CONJURE_TAG_DOM_NODE__ = __tagNode;",
    "  window.__CONJURE_INSTALL_DOM_TAG_OBSERVER__ = function () {",
    "    if (typeof MutationObserver === 'undefined') return;",
    "    var root = document.documentElement || document.body;",
    "    if (!root) return;",
    "    var observer = new MutationObserver(function (mutations) {",
    "      for (var mutationIndex = 0; mutationIndex < mutations.length; mutationIndex += 1) {",
    "        var mutation = mutations[mutationIndex];",
    "        var target = mutation.target;",
    "        var ownedTarget = target && target.closest ? target.closest('[data-conjure-mod-id=\"' + __conjureModId + '\"]') : null;",
    "        if (!ownedTarget) continue;",
    "        for (var nodeIndex = 0; nodeIndex < mutation.addedNodes.length; nodeIndex += 1) {",
    "          __tagNode(mutation.addedNodes[nodeIndex]);",
    "        }",
    "      }",
    "    });",
    "    observer.observe(root, { childList: true, subtree: true });",
    "  };",
    "  document.createElement = function () {",
    "    return __tagNode(__originalCreateElement.apply(document, arguments));",
    "  };",
    "  document.createElementNS = function () {",
    "    return __tagNode(__originalCreateElementNS.apply(document, arguments));",
    "  };",
    "  window.__CONJURE_RESTORE_DOM_TAGGING__ = function () {",
    "    document.createElement = __originalCreateElement;",
    "    document.createElementNS = __originalCreateElementNS;",
    "    delete window.__CONJURE_RESTORE_DOM_TAGGING__;",
    "    delete window.__CONJURE_TAG_DOM_NODE__;",
    "    delete window.__CONJURE_INSTALL_DOM_TAG_OBSERVER__;",
    "  };",
    "  window.setTimeout(function () {",
    "    if (window.__CONJURE_RESTORE_DOM_TAGGING__) window.__CONJURE_RESTORE_DOM_TAGGING__();",
    "  }, 1000);",
    "})();"
  ].join("\n");

const buildDomTaggingFinalizerCode = (modIdLiteral: string): string =>
  [
    "(function () {",
    `  var __conjureModId = ${modIdLiteral};`,
    "  var __tagNode = window.__CONJURE_TAG_DOM_NODE__;",
    "  if (__tagNode) {",
    "    var __owned = document.querySelectorAll('[data-conjure-mod-id]');",
    "    for (var __index = 0; __index < __owned.length; __index += 1) {",
    "      if (__owned[__index].getAttribute('data-conjure-mod-id') === __conjureModId) {",
    "        __tagNode(__owned[__index]);",
    "      }",
    "    }",
    "  }",
    "  if (window.__CONJURE_INSTALL_DOM_TAG_OBSERVER__) window.__CONJURE_INSTALL_DOM_TAG_OBSERVER__();",
    "  if (window.__CONJURE_RESTORE_DOM_TAGGING__) window.__CONJURE_RESTORE_DOM_TAGGING__();",
    "})();"
  ].join("\n");
